blank_issues_enabled: false
contact_links:
    - name: Questions & discussions
      url: https://github.com/yell0wsuit/cuttherope-dx/discussions
      about: For general questions or discussions, please visit our Discussions page.
